version: "3.9"
services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=test
      - MARIADB_ROOT_PASSWORD=example

  api:
    build: ./api/ContainerLabs1.Api
    depends_on:
      - db

  app:
    build: ./app1
  
  proxy:
    build: ./proxy
    ports:
      - 9000:80
    depends_on:
      - api
      - app

volumes:
  db-data: