version: "3.9"
services:
  db:
    build: ./src/MariaDb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --silent']
      interval: 3s
      retries: 5
      start_period: 30s

  minio:
    hostname: minio
    image: quay.io/minio/minio:RELEASE.2022-11-11T03-44-20Z
    command: server --console-address ":9001" http://minio/data{1...2}
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio-data-1:/data1
      - minio-data-2:/data2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  api:
    build: ./src/Api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  app:
    build: ./src/App1
  
  proxy:
    build: ./src/Proxy
    ports:
      - 9002:80
      - 9000:9000
      - 9001:9001
    depends_on:
      - api
      - app

volumes:
  db-data:
  minio-data-1:
  minio-data-2: