version: "3.9"
services:
  db:
    build: ./mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --silent']
      interval: 3s
      retries: 5
      start_period: 30s

  api:
    build: ./api/ContainerLabs1.Api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  app:
    build: ./app1
  
  proxy:
    build: ./proxy
    ports:
      - 9000:80
    depends_on:
      - api
      - app

volumes:
  db-data: